### ISSUE TITLE
**fix storybook and webpack building issue**

### ISSUE THREAD

**Issue by atwfk** [m3ntorship/pickify-frontend#29]
how to reproduce the problem:
   - open the project and run yarn storybook
you will notice that webpack has an infinite loop building when watching the project files

**Comment by Nilegfx** [comment]
increasing file watchers help solving this problem in addition to the PR that @atwfk will open soon

to get the current watchers count: 
```sh 
cat /proc/sys/fs/inotify/max_user_watches
```

to check which process eats more CPU resources use [this script](https://github.com/fatso83/dotfiles/blob/master/utils/scripts/inotify-consumers) from [this answer](https://stackoverflow.com/a/60602320/2637185) 

1. download the script, name the file something like inotify-consumers.sh at any directory
2. run `chmod +x ~/Downloads/inotify-consumers.sh`
3. run ./inotify-consumers.sh

to change number of watchers add this line `fs.inotify.max_user_watches=524288` at the end of `/etc/sysctl.conf` file

**Comment by Nilegfx** [comment]
in order to use the glob patterns correctly: 
`../@(modules|pages)/**/*.stories.@(js|mdx|tsx)`

we have to use different webpack builder from storybook. the default one is webpack4 and I updated the issue with the solution here

https://github.com/storybookjs/storybook/issues/14342#issuecomment-835647922
